import { StyleSheet } from 'react-native';
import { COLORS } from '@/constants/colors';
import { FONTS } from '@/constants/fonts';

export const aiStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: COLORS.background,
		paddingHorizontal: 20,
		paddingTop: 20,
	},
	title: {
		fontSize: 28,
		fontFamily: FONTS.bold,
		color: COLORS.text,
		marginBottom: 10,
	},
	subtitle: {
		fontSize: 16,
		color: COLORS.textLight,
		marginBottom: 30,
		lineHeight: 22,
		fontFamily: FONTS.regular,
	},
	buttonContainer: {
		gap: 20,
		marginBottom: 30,
	},
	actionButton: {
		backgroundColor: COLORS.primary,
		paddingVertical: 16,
		paddingHorizontal: 24,
		borderRadius: 12,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 12,
		shadowColor: COLORS.primary,
		shadowOffset: {
			width: 0,
			height: 4,
		},
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 8,
	},
	secondaryButton: {
		backgroundColor: COLORS.white,
		borderWidth: 2,
		borderColor: COLORS.primary,
		shadowColor: COLORS.shadow,
		shadowOpacity: 0.1,
	},
	buttonText: {
		color: COLORS.white,
		fontSize: 16,
		fontFamily: FONTS.semibold,
	},
	secondaryButtonText: {
		color: COLORS.primary,
	},
	imageContainer: {
		backgroundColor: COLORS.white,
		borderRadius: 16,
		padding: 20,
		marginBottom: 20,
		shadowColor: COLORS.shadow,
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.1,
		shadowRadius: 8,
		elevation: 4,
	},
	selectedImage: {
		width: '100%',
		height: 200,
		borderRadius: 12,
		resizeMode: 'cover',
	},
	imagePlaceholder: {
		width: '100%',
		height: 200,
		backgroundColor: COLORS.background,
		borderRadius: 12,
		alignItems: 'center',
		justifyContent: 'center',
		borderWidth: 2,
		borderColor: COLORS.border,
		borderStyle: 'dashed',
	},
	placeholderText: {
		color: COLORS.textLight,
		fontSize: 16,
		marginTop: 10,
		textAlign: 'center',
	},
	resultsContainer: {
		backgroundColor: COLORS.white,
		borderRadius: 16,
		padding: 20,
		marginBottom: 20,
		shadowColor: COLORS.shadow,
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.1,
		shadowRadius: 8,
		elevation: 4,
	},
	resultTitle: {
		fontSize: 20,
		fontFamily: FONTS.bold,
		color: COLORS.text,
		marginBottom: 15,
	},
	dishName: {
		fontSize: 18,
		fontFamily: FONTS.semibold,
		color: COLORS.primary,
		marginBottom: 8,
	},
	confidence: {
		fontSize: 14,
		color: COLORS.textLight,
		marginBottom: 15,
		fontFamily: FONTS.regular,
	},
	recipeName: {
		fontSize: 18,
		fontFamily: FONTS.bold,
		color: COLORS.text,
		marginBottom: 15,
	},
	sectionTitle: {
		fontSize: 16,
		fontFamily: FONTS.semibold,
		color: COLORS.text,
		marginTop: 15,
		marginBottom: 10,
	},
	ingredientItem: {
		fontSize: 14,
		color: COLORS.text,
		paddingVertical: 4,
		paddingLeft: 10,
		fontFamily: FONTS.regular,
	},
	instructionItem: {
		fontSize: 14,
		color: COLORS.text,
		paddingVertical: 6,
		paddingLeft: 10,
		lineHeight: 20,
		fontFamily: FONTS.regular,
	},
	instructionNumber: {
		fontFamily: FONTS.semibold,
		color: COLORS.primary,
	},
	loadingContainer: {
		backgroundColor: COLORS.white,
		borderRadius: 16,
		padding: 30,
		marginBottom: 20,
		alignItems: 'center',
		shadowColor: COLORS.shadow,
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.1,
		shadowRadius: 8,
		elevation: 4,
	},
	loadingText: {
		fontSize: 16,
		color: COLORS.text,
		marginTop: 15,
		textAlign: 'center',
	},
	errorContainer: {
		backgroundColor: '#ffebee',
		borderRadius: 12,
		padding: 16,
		marginBottom: 20,
		borderLeftWidth: 4,
		borderLeftColor: '#f44336',
	},
	errorText: {
		color: '#c62828',
		fontSize: 14,
		lineHeight: 20,
	},
	resetButton: {
		backgroundColor: COLORS.textLight,
		paddingVertical: 12,
		paddingHorizontal: 20,
		borderRadius: 8,
		marginTop: 15,
	},
	resetButtonText: {
		color: COLORS.white,
		fontSize: 14,
		fontFamily: FONTS.medium,
		textAlign: 'center',
	},
});
