import { StyleSheet } from 'react-native';
import { COLORS } from '@/constants/colors';
import { FONTS } from '@/constants/fonts';

export const favoritesStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: COLORS.background,
	},
	modernHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingHorizontal: 20,
		paddingVertical: 16,
		backgroundColor: COLORS.background,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.05,
		shadowRadius: 4,
		elevation: 2,
	},
	headerLeft: {
		flexDirection: 'row',
		alignItems: 'center',
	},
	headerTitle: {
		fontSize: 24,
		fontFamily: FONTS.extrabold,
		color: COLORS.text,
		marginLeft: 12,
		letterSpacing: -0.5,
	},
	headerRight: {
		flexDirection: 'row',
		alignItems: 'center',
	},
	iconButton: {
		width: 40,
		height: 40,
		borderRadius: 12,
		backgroundColor: COLORS.card,
		justifyContent: 'center',
		alignItems: 'center',
		marginRight: 8,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 2,
		elevation: 2,
	},
	header: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingHorizontal: 20,
		paddingVertical: 16,
	},
	title: {
		fontSize: 32,
		fontFamily: FONTS.extrabold,
		color: COLORS.text,
		letterSpacing: -0.5,
	},
	logoutButton: {
		width: 40,
		height: 40,
		borderRadius: 12,
		backgroundColor: COLORS.card,
		justifyContent: 'center',
		alignItems: 'center',
		shadowColor: COLORS.shadow,
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 2,
	},
	statsContainer: {
		flexDirection: 'row',
		paddingHorizontal: 16,
		marginTop: 24,
		gap: 12,
	},
	statCard: {
		flex: 1,
		backgroundColor: COLORS.card,
		borderRadius: 16,
		padding: 16,
		alignItems: 'center',
		shadowColor: COLORS.shadow,
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.05,
		shadowRadius: 4,
		elevation: 2,
	},
	statNumber: {
		fontSize: 24,
		fontFamily: FONTS.bold,
		color: COLORS.primary,
		marginBottom: 4,
	},
	statLabel: {
		fontSize: 12,
		fontFamily: FONTS.regular,
		color: COLORS.textLight,
		textAlign: 'center',
	},
	statIcon: {
		width: 40,
		height: 40,
		borderRadius: 20,
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: 8,
	},
	statValue: {
		fontSize: 20,
		fontFamily: FONTS.bold,
		color: COLORS.text,
		marginBottom: 4,
	},
	recipesSection: {
		paddingHorizontal: 16,
		marginTop: 24,
		paddingBottom: 32,
	},
	recipesGrid: {
		gap: 16,
	},
	row: {
		justifyContent: 'space-between',
	},
	emptyState: {
		alignItems: 'center',
		paddingVertical: 64,
		paddingHorizontal: 32,
	},
	emptyIconContainer: {
		width: 120,
		height: 120,
		borderRadius: 60,
		backgroundColor: COLORS.card,
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: 24,
		borderWidth: 2,
		borderColor: COLORS.border,
		borderStyle: 'dashed',
	},
	emptyTitle: {
		fontSize: 24,
		fontFamily: FONTS.bold,
		color: COLORS.text,
		marginBottom: 24,
	},
	exploreButton: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: COLORS.primary,
		paddingHorizontal: 24,
		paddingVertical: 12,
		borderRadius: 24,
		gap: 8,
	},
	exploreButtonText: {
		fontSize: 16,
		fontFamily: FONTS.semibold,
		color: COLORS.white,
	},
});
