import { StyleSheet } from 'react-native';
import { COLORS } from '@/constants/colors';
import { FONTS } from '@/constants/fonts';

export const searchStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: COLORS.background,
	},
	loadingState: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		rowGap: 12,
		paddingHorizontal: 24,
	},
	loadingStateText: {
		color: COLORS.white,
		fontFamily: FONTS.medium,
		fontSize: 15,
		textAlign: 'center',
	},
	modernHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 20,
		paddingVertical: 12,
		backgroundColor: COLORS.background,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.05,
		shadowRadius: 4,
		elevation: 2,
	},
	iconButton: {
		width: 48,
		height: 48,
		backgroundColor: COLORS.card,
		borderRadius: 12,
		justifyContent: 'center',
		alignItems: 'center',
		marginLeft: 12,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 2,
		elevation: 2,
	},
	searchSection: {
		paddingHorizontal: 16,
		paddingTop: 16,
	},
	searchContainer: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: COLORS.card,
		borderRadius: 12,
		paddingHorizontal: 12,
		paddingVertical: 14,
		elevation: 2,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 2,
	},
	searchIcon: {
		marginRight: 8,
	},
	searchInput: {
		flex: 1,
		fontSize: 16,
		color: COLORS.text,
		fontFamily: FONTS.regular,
	},
	clearButton: {
		padding: 4,
	},
	quickFilters: {
		marginTop: 20,
	},
	filterLabel: {
		fontSize: 16,
		fontFamily: FONTS.semibold,
		color: COLORS.text,
		marginBottom: 12,
	},
	filterButtons: {
		flexDirection: 'row',
		gap: 12,
	},
	quickFilterButton: {
		backgroundColor: COLORS.card,
		paddingHorizontal: 16,
		paddingVertical: 8,
		borderRadius: 20,
		borderWidth: 1,
		borderColor: COLORS.border,
	},
	activeQuickFilter: {
		backgroundColor: COLORS.primary,
		borderColor: COLORS.primary,
	},
	quickFilterText: {
		fontSize: 14,
		fontFamily: FONTS.medium,
		color: COLORS.text,
	},
	activeQuickFilterText: {
		color: COLORS.white,
	},
	resultsSection: {
		flex: 1,
		paddingHorizontal: 16,
		marginTop: 8,
	},
	resultsHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: 16,
		marginTop: 16,
	},
	resultsTitle: {
		fontSize: 18,
		fontFamily: FONTS.bold,
		color: COLORS.text,
		flex: 1,
	},
	resultsCount: {
		fontSize: 14,
		color: COLORS.textLight,
		fontFamily: FONTS.medium,
	},
	loadingContainer: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		rowGap: 12,
	},
	loadingText: {
		color: COLORS.white,
		fontFamily: FONTS.medium,
		fontSize: 14,
	},
	recipesGrid: {
		gap: 16,
		paddingBottom: 32,
	},
	row: {
		justifyContent: 'space-between',
	},
	emptyState: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		paddingVertical: 64,
	},
	emptyTitle: {
		fontSize: 20,
		fontFamily: FONTS.bold,
		color: COLORS.text,
		marginTop: 16,
		marginBottom: 8,
	},
	emptyDescription: {
		fontSize: 14,
		color: COLORS.textLight,
		textAlign: 'center',
		lineHeight: 20,
		fontFamily: FONTS.regular,
	},
	searchTypeToggle: {
		flexDirection: 'row',
		marginHorizontal: 16,
		marginTop: 12,
		marginBottom: 8,
		backgroundColor: COLORS.card,
		borderRadius: 12,
		padding: 4,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.1,
		shadowRadius: 2,
		elevation: 2,
	},
	toggleButton: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 8,
		gap: 6,
	},
	toggleButtonActive: {
		backgroundColor: COLORS.primary,
		shadowColor: COLORS.primary,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.2,
		shadowRadius: 4,
		elevation: 2,
	},
	toggleButtonText: {
		fontSize: 14,
		fontFamily: FONTS.medium,
		color: COLORS.text,
	},
	toggleButtonTextActive: {
		color: COLORS.white,
		fontFamily: FONTS.semibold,
	},
	heroWrapper: {
		paddingHorizontal: 20,
		paddingTop: 12,
	},
	heroCard: {
		borderRadius: 24,
		padding: 20,
		borderWidth: 1,
		borderColor: 'rgba(255,255,255,0.1)',
	},
	heroTextGroup: {
		rowGap: 8,
	},
	heroEyebrow: {
		fontSize: 12,
		textTransform: 'uppercase',
		letterSpacing: 1,
		color: 'rgba(255,255,255,0.7)',
		fontFamily: FONTS.semibold,
	},
	heroTitle: {
		fontSize: 26,
		fontFamily: FONTS.extrabold,
		color: COLORS.white,
	},
	heroSubtitle: {
		color: 'rgba(255,255,255,0.8)',
		fontFamily: FONTS.regular,
		fontSize: 14,
		lineHeight: 20,
	},
	heroButtons: {
		flexDirection: 'row',
		columnGap: 12,
		marginTop: 16,
	},
	heroButton: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		columnGap: 8,
		borderRadius: 16,
		paddingVertical: 12,
		borderWidth: 1,
		borderColor: 'rgba(255,255,255,0.2)',
	},
	heroButtonActive: {
		backgroundColor: 'rgba(0,0,0,0.4)',
		borderColor: COLORS.primary,
	},
	heroButtonText: {
		color: COLORS.white,
		fontFamily: FONTS.semibold,
	},
	promptsContainer: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
		paddingHorizontal: 20,
		paddingTop: 12,
	},
	promptChip: {
		flexDirection: 'row',
		alignItems: 'center',
		columnGap: 6,
		paddingHorizontal: 14,
		paddingVertical: 8,
		borderRadius: 999,
		borderWidth: 1,
		borderColor: 'rgba(255,255,255,0.2)',
		backgroundColor: 'rgba(0,0,0,0.25)',
	},
	promptChipActive: {
		borderColor: COLORS.primary,
		backgroundColor: 'rgba(255,255,255,0.15)',
	},
	promptChipText: {
		color: COLORS.white,
		fontFamily: FONTS.medium,
		fontSize: 13,
	},
	recentContainer: {
		paddingHorizontal: 20,
		paddingTop: 12,
	},
	recentLabel: {
		fontSize: 13,
		fontFamily: FONTS.medium,
		color: 'rgba(255,255,255,0.7)',
		marginBottom: 10,
	},
	recentChips: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 10,
	},
	recentChip: {
		paddingHorizontal: 14,
		paddingVertical: 8,
		borderRadius: 16,
		borderWidth: 1,
		borderColor: 'rgba(255,255,255,0.15)',
	},
	recentChipText: {
		color: COLORS.white,
		fontFamily: FONTS.medium,
		fontSize: 13,
	},
});
